//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyUKR.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EasyUkrEntities1 : DbContext
    {
        public EasyUkrEntities1()
            : base("name=EasyUkrEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GrammarAnswer> GrammarAnswers { get; set; }
        public virtual DbSet<GrammarTask> GrammarTasks { get; set; }
        public virtual DbSet<GrammarTopic> GrammarTopics { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<Translate> Translates { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
        public virtual DbSet<UserHistory> UserHistories { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<Word> Words { get; set; }
    }
}
