//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyUKR.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrammarAnswer
    {
        public int id { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> IsCorrect { get; set; }
        public Nullable<int> idTask { get; set; }
    
        public virtual GrammarTask GrammarTask { get; set; }
    }
}
