//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyUKR.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserHistory
    {
        public int HID { get; set; }
        public int UsID { get; set; }
        public Nullable<int> TopicID { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<int> Progress { get; set; }
        public string Info { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
